language: c

matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode7.3

sudo: required

addons:
  apt:
    packages:
      - libpam0g-dev
      - libssl-dev
      - libcurl4-openssl-dev
      - time
      - gss-ntlmssp

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install openssl ; fi

script: 
      - cd Unix && ./regress
